### ISSUE TITLE
Typo in python script name

### ISSUE THREAD

**Issue by criling** [CiscoSE/LTRPRG-1100#45]
The guide states "Run the dnac-get-hosts.py Python script with the python dnac-get-hosts.py command, for example (output truncated for brevity):"

but right below, the cli output shows us running the wrong script:

(pythonenv) $ python dnac-get-devices.py

**Comment by magalazk** [comment]
Created branch 'issue45' to fix. Pending review/merge. Thanks @criling

**Comment by curtissmith** [comment]
Reviewed, approved, and merged with pull request.
